[project]
name = "advent"
version = "0.1.0"
description = "I hope you all have a good month!"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = [
    "venv",
]
